"""Git hook installation, so the graph does not go stale.

A knowledge source that agents treat as the truth has to *be* current. A graph
regenerated by hand drifts within hours, and an agent making decisions from a
two-hour-old graph reintroduces exactly the drift this project exists to close.

Post-commit is the default rather than pre-commit. Regenerating a multi-megabyte
graph inside the commit adds seconds to every commit and mutates state mid-commit;
that is the kind of friction that gets a tool uninstalled.
"""

from __future__ import annotations

import stat
import subprocess
from pathlib import Path

BEGIN = "# >>> lineagelens >>>"
END = "# <<< lineagelens <<<"

SUPPORTED = ("post-commit", "pre-commit")

_BODY = """\
{begin}
# Regenerate the LineageLens graph so agents and the UI see current state.
# Managed block: edit outside the markers, or run `lineagelens hook uninstall`.
#
# $CI guard: CI regenerates the graph as an explicit build step.
# $LINEAGELENS_HOOK guard: stops recursion if analysis ever commits.
# mkdir first: redirecting into a directory that does not exist yet fails the
# whole hook, and `|| true` would swallow it, leaving the graph silently stale.
if [ -z "$CI" ] && [ -z "$LINEAGELENS_HOOK" ]; then
    mkdir -p .lineagelens
    LINEAGELENS_HOOK=1 lineagelens analyze . --quiet \\
        >> .lineagelens/hook.log 2>&1 || true
fi
{end}
"""


class HookError(RuntimeError):
    """Raised when a hook cannot be installed or removed safely."""


def hooks_dir(project: Path) -> Path:
    """Resolve the hooks directory via git itself.

    Asking git rather than assuming ``.git/hooks`` is what makes this work inside
    a worktree or with ``core.hooksPath`` set.
    """
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=project,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as e:
        raise HookError(f"{project} does not look like a git repository ({e})") from e
    return (project / completed.stdout.strip()).resolve()


def _managed_block(text: str) -> tuple[int, int] | None:
    """Span of the managed block within an existing hook, if present."""
    if BEGIN not in text or END not in text:
        return None
    start = text.index(BEGIN)
    end = text.index(END) + len(END)
    return start, end


def install(project: Path, kind: str = "post-commit", force: bool = False) -> Path:
    """Install or refresh the managed block in a hook.

    Appends between markers so a hand-written hook survives. Refuses to touch a
    foreign hook without ``force``, because silently rewriting someone's commit
    tooling is not a reasonable thing for an analysis tool to do.
    """
    if kind not in SUPPORTED:
        raise HookError(f"Unsupported hook {kind!r}; expected one of {', '.join(SUPPORTED)}")

    directory = hooks_dir(project)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / kind
    block = _BODY.format(begin=BEGIN, end=END)

    if not path.exists():
        path.write_text(f"#!/bin/sh\n{block}", encoding="utf-8")
    else:
        existing = path.read_text(encoding="utf-8")
        span = _managed_block(existing)
        if span is not None:
            start, end = span
            path.write_text(existing[:start] + block.rstrip("\n") + existing[end:], encoding="utf-8")
        elif existing.strip() and not force:
            raise HookError(
                f"{path} already exists and was not created by LineageLens.\n"
                f"Re-run with --force to append a managed block to it."
            )
        else:
            separator = "" if existing.endswith("\n") or not existing else "\n"
            path.write_text(f"{existing}{separator}{block}", encoding="utf-8")

    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def uninstall(project: Path, kind: str = "post-commit") -> bool:
    """Remove only the managed block. Returns whether anything was removed."""
    path = hooks_dir(project) / kind
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    span = _managed_block(text)
    if span is None:
        return False
    start, end = span
    remainder = (text[:start] + text[end:]).strip()
    # If nothing but the shebang is left, the file was ours alone.
    if remainder in ("", "#!/bin/sh", "#!/bin/bash"):
        path.unlink()
    else:
        path.write_text(text[:start] + text[end:].lstrip("\n"), encoding="utf-8")
    return True


def status(project: Path) -> dict[str, bool]:
    """Which supported hooks currently carry a managed block."""
    try:
        directory = hooks_dir(project)
    except HookError:
        return {kind: False for kind in SUPPORTED}
    result = {}
    for kind in SUPPORTED:
        path = directory / kind
        result[kind] = (
            path.exists() and _managed_block(path.read_text(encoding="utf-8")) is not None
        )
    return result


__all__ = ["BEGIN", "END", "SUPPORTED", "HookError", "hooks_dir", "install", "status", "uninstall"]
