"""Capability reporting, generated rather than declared (issue #51 §12).

The schema-3 version of this module was a hand-written dict. It declared four
relation kinds while nine were emitted, omitted ``REFERENCES`` (657 edges) and
``ANNOTATES`` (235), and listed tools that returned nothing -- so agents were
told to trust a contract that misdescribed 19% of the graph.

Prose cannot describe behaviour it does not observe. So everything here is
*measured*:

* relation and node kinds come from the enums the store actually persists
* per-language support comes from the conformance suite's golden results
  (``conformance/matrix.json``), regenerated by running it
* grammar and type-resolver availability is probed on **this** installation,
  because whether Java has type-accurate resolution depends on whether a JDK is
  on this machine

That last point matters more than it sounds. An agent asking about Go needs to
know whether a negative answer means "nothing calls this" or "Go was skipped
here", and only a per-install probe can say.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .core import (
    CONTRACT_EDGES,
    DATA_EDGES,
    PERSISTED_EDGES,
    SCHEMA_VERSION,
    STRUCTURAL_EDGES,
    BoundaryKind,
    ContractKind,
    EdgeKind,
    EvidenceTier,
    Intent,
    NodeKind,
    Resolution,
)

#: Where the conformance suite writes its measured per-language results.
MATRIX_PATH = Path(__file__).resolve().parent / "conformance" / "matrix.json"

#: Capabilities the matrix reports per language.
CAPABILITIES = (
    "nodes", "calls", "inherits", "implements", "dataflow", "contracts",
)


def relation_kinds() -> list[str]:
    """Every edge kind the store can hold, from the enum itself.

    Derived rather than listed, so it cannot drift from what is emitted.
    """
    return sorted(str(k) for k in PERSISTED_EDGES)


def node_kinds() -> list[str]:
    return sorted(k.value for k in NodeKind)


def measured_matrix() -> dict[str, dict[str, Any]]:
    """Per-language conformance results, or ``{}`` if never generated.

    Absence is reported as absence. Fabricating a plausible matrix here would
    reproduce exactly the schema-3 failure this module exists to correct.
    """
    if not MATRIX_PATH.is_file():
        return {}
    try:
        payload = json.loads(MATRIX_PATH.read_text("utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload.get("languages", {})


def installed_tiers() -> dict[str, dict[str, str]]:
    """Grammar and type-resolver availability on this machine (§7.2)."""
    from .extract.langs import ParserRegistry, grammar_version
    from .resolve.oracles import OracleRegistry

    parsers = ParserRegistry()
    available = parsers.available()
    oracles = OracleRegistry()

    out: dict[str, dict[str, str]] = {}
    for dialect, version in sorted(available.items()):
        from .extract.langs import language_of

        lang = language_of(dialect)
        entry = out.setdefault(lang, {"tier_a": "missing", "tier_b": "missing"})
        entry["tier_a"] = f"tree-sitter {version}"

    for lang, tools in oracles.availability().items():
        entry = out.setdefault(lang, {"tier_a": "missing", "tier_b": "missing"})
        best = next(
            (f"{name} ({state})" for name, state in sorted(tools.items())
             if state != "missing"),
            "missing",
        )
        entry["tier_b"] = best

    for lang, entry in out.items():
        entry["grammar_version"] = grammar_version(lang) or "n/a"
        # Tier A is always available once a grammar loads, and it is a real
        # tier: it resolves declared types, lexical scope and self-receivers,
        # and records an ambiguity rather than guessing when it cannot. Saying
        # only "tier B: missing" invited the reading that the language was
        # unsupported, which is what made the default index skip 25 files.
        if entry["tier_b"] == "missing":
            entry["tier_b"] = "none (Tier A resolution)"
    return out


def capability_matrix(project: Path | None = None) -> dict[str, Any]:
    """The full, measured capability report served by ``get_ontology``."""
    measured = measured_matrix()
    installed = installed_tiers()

    languages: dict[str, Any] = {}
    for lang in sorted(set(measured) | set(installed)):
        entry: dict[str, Any] = {
            "tier_a": installed.get(lang, {}).get("tier_a", "missing"),
            "tier_b": installed.get(lang, {}).get("tier_b", "missing"),
        }
        conformance = measured.get(lang)
        if conformance:
            entry["capabilities"] = {
                name: conformance.get(name, "untested") for name in CAPABILITIES
            }
        else:
            # Untested is not the same as unsupported, and saying so is the
            # difference between an honest gap and a false claim.
            entry["capabilities"] = dict.fromkeys(CAPABILITIES, "untested")
        languages[lang] = entry

    report: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "generated": MATRIX_PATH.is_file(),
        "node_kinds": node_kinds(),
        "relation_kinds": relation_kinds(),
        "relation_groups": {
            "structural": sorted(str(k) for k in STRUCTURAL_EDGES),
            "control": [EdgeKind.CALLS.value, EdgeKind.REFERENCES.value],
            "data": sorted(str(k) for k in DATA_EDGES),
            "contract": sorted(str(k) for k in CONTRACT_EDGES),
        },
        "evidence_tiers": [t.value for t in EvidenceTier],
        "resolution_values": [r.value for r in Resolution],
        "boundary_kinds": [b.value for b in BoundaryKind],
        "contract_kinds": [c.value for c in ContractKind],
        "intents": [i.value for i in Intent],
        "languages": languages,
        "guarantees": _GUARANTEES,
        "limitations": _LIMITATIONS,
    }

    if project is not None:
        report["project"] = _project_facts(project)
    return report


def _project_facts(project: Path) -> dict[str, Any]:
    """What this specific index contains, if one exists."""
    from .store import DB_FILENAME, GraphNotFound, GraphStore, SchemaMismatch

    try:
        with GraphStore.open(project / ".lineagelens" / DB_FILENAME) as store:
            row = store.conn.execute(
                "SELECT built_at, commit_sha, build_digest "
                "FROM graph_meta WHERE id = 1"
            ).fetchone()
            # Only languages something was actually extracted from. A `files`
            # row exists for skipped files too, so selecting every distinct
            # lang reported a language as present while also reporting it as
            # skipped -- two contradictory claims in the same output.
            langs = [
                r["lang"]
                for r in store.conn.execute(
                    "SELECT DISTINCT lang FROM files WHERE parse_status IN "
                    "('ok', 'partial')"
                )
            ]
            skipped = {
                f"{r['lang']} ({r['n']} files)": r["skip_reason"]
                for r in store.conn.execute(
                    "SELECT lang, skip_reason, count(*) n FROM files "
                    "WHERE skip_reason IS NOT NULL GROUP BY lang, skip_reason"
                )
            }
            return {
                "indexed": True,
                "languages_present": sorted(langs),
                "languages_skipped": skipped,
                "counts": store.counts(),
                "edge_kinds_present": store.edge_kind_counts(),
                "built_at": row["built_at"] if row else None,
                "build_digest": row["build_digest"] if row else None,
            }
    except (GraphNotFound, SchemaMismatch) as exc:
        return {"indexed": False, "reason": str(exc)}


#: What a caller may rely on. Each is enforced by a test, named so a reader can
#: go and check rather than take it on trust.
_GUARANTEES = [
    "Every edge has both endpoints present as real nodes (foreign keys, plus a "
    "post-build assertion).",
    "Every observed reference becomes an edge or an unresolved_refs row; the "
    "per-file coverage row must balance, enforced by a CHECK constraint.",
    "When several candidates match a reference, no edge is emitted and the "
    "ambiguity is recorded with its candidate set.",
    "A missing grammar or type resolver skips the file with a recorded reason; "
    "it never falls back to name matching.",
    "Two indexes of one commit produce the same build digest.",
    "Contract edges are always heuristic, so they can be filtered out "
    "independently of syntactic facts.",
    "Cross-language edges exist only through contract nodes, never through a "
    "shared identifier.",
]

#: What a caller must not assume. Stated because a limitation a tool knows
#: about is a boundary record, and one it does not is a wrong answer.
_LIMITATIONS = [
    "Data flow is intraprocedural plus signature binding and return flow. "
    "Aliasing, container contents and closure capture are boundaries, not edges.",
    "Go interface satisfaction is structural and Rust blanket impls have no "
    "single target; IMPLEMENTS is partial for both.",
    "Java and C# overload resolution needs a type resolver; without Tier B "
    "those languages are skipped rather than approximated.",
    "Contract detection covers the shipped adapters. A framework with no "
    "adapter is reported as an unclaimed declaration, not silently omitted.",
    "A contract key assembled at runtime cannot be joined; the resolvable "
    "prefix is kept and a dynamic_contract_key boundary recorded.",
    "dataflow=lazy defers data-flow edges; coverage reports status 'lazy' "
    "rather than 'computed'.",
]


def ontology_instructions(project: Path | None = None) -> str:
    """The instruction block an MCP client sees on connect.

    Short on purpose. It names the tools worth reaching for first and the one
    habit that matters -- read the coverage envelope before trusting a negative
    answer -- rather than restating the whole matrix, which ``get_ontology``
    serves on request.
    """
    matrix = capability_matrix(project)
    langs = matrix.get("languages", {})
    ready = sorted(
        lang for lang, entry in langs.items() if entry["tier_a"] != "missing"
    )
    project_facts = matrix.get("project", {})

    lines = [
        f"LineageLens schema {SCHEMA_VERSION}: a deterministic code graph with "
        f"control flow, data flow and cross-service contracts.",
        "",
        f"Languages available here: {', '.join(ready) or 'none'}.",
    ]

    if project_facts.get("indexed"):
        counts = project_facts.get("counts", {})
        lines.append(
            f"This index: {counts.get('nodes', 0):,} nodes, "
            f"{counts.get('edges', 0):,} edges, "
            f"{counts.get('unresolved_refs', 0):,} unresolved references."
        )
        skipped = project_facts.get("languages_skipped") or {}
        if skipped:
            lines.append(
                "Skipped languages: "
                + ", ".join(f"{k} ({v})" for k, v in sorted(skipped.items()))
            )
    else:
        lines.append(
            "No index yet. Run `lineagelens index <path>` before querying."
        )

    lines += [
        "",
        "Which tool:",
        "  fixing a bug        impact_of('file.py:412'), map_stacktrace, dataflow_of",
        "  understanding flow  find_paths, trace_flow, callers_of",
        "  planning a feature  similar_flows first, then contract_map",
        "  crossing a service  contract_map -- no call edge describes these",
        "  an answer looks off explain(a, b) names the evidence and provenance",
        "",
        "Two habits:",
        "  Every response carries a `coverage` envelope. Read it before "
        "trusting a negative answer -- it reports boundaries crossed, files "
        "skipped, and frameworks present but unmodelled.",
        "  Pass intent='plan' when surveying and intent='precise' when "
        "debugging. Precise adds verbatim source and data flow; plan is far "
        "cheaper and is the default for traversal tools.",
        "",
        "Unresolved is not the same as absent: a reference the resolver could "
        "not pin down is recorded with its candidates rather than guessed at, "
        "so ambiguity is visible instead of being resolved arbitrarily.",
    ]
    return "\n".join(lines)
