"""Git hook installation.

A knowledge source agents treat as truth has to be current, and a graph
regenerated by hand drifts within hours. But installing a hook means writing into
someone's commit tooling, so the safety properties matter as much as the feature:
never clobber a foreign hook, always be idempotent, always be cleanly removable.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from lineagelens.hooks import BEGIN, HookError, hooks_dir, install, status, uninstall


def git_repo(root: Path) -> Path:
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    return root


def test_install_creates_an_executable_hook(tmp_path):
    root = git_repo(tmp_path)
    path = install(root)

    assert path.exists()
    assert path.name == "post-commit"
    assert BEGIN in path.read_text()
    assert path.stat().st_mode & 0o111, "hook must be executable or git ignores it"


def test_install_is_idempotent(tmp_path):
    root = git_repo(tmp_path)
    install(root)
    path = install(root)
    assert path.read_text().count(BEGIN) == 1


def test_a_foreign_hook_is_not_clobbered(tmp_path):
    root = git_repo(tmp_path)
    path = hooks_dir(root) / "post-commit"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\necho mine\n")

    with pytest.raises(HookError, match="--force"):
        install(root)
    assert path.read_text() == "#!/bin/sh\necho mine\n", "the file must be untouched"


def test_force_appends_and_preserves_the_existing_hook(tmp_path):
    root = git_repo(tmp_path)
    path = hooks_dir(root) / "post-commit"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\necho mine\n")

    install(root, force=True)
    text = path.read_text()
    assert "echo mine" in text and BEGIN in text


def test_uninstall_leaves_a_users_own_hook_intact(tmp_path):
    root = git_repo(tmp_path)
    path = hooks_dir(root) / "post-commit"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\necho mine\n")
    install(root, force=True)

    assert uninstall(root) is True
    assert path.exists()
    assert "echo mine" in path.read_text()
    assert BEGIN not in path.read_text()


def test_uninstall_removes_a_hook_that_was_entirely_ours(tmp_path):
    root = git_repo(tmp_path)
    path = install(root)
    assert uninstall(root) is True
    assert not path.exists()


def test_uninstall_is_safe_when_nothing_is_installed(tmp_path):
    root = git_repo(tmp_path)
    assert uninstall(root) is False


def test_status_reports_each_supported_hook(tmp_path):
    root = git_repo(tmp_path)
    assert status(root) == {"post-commit": False, "pre-commit": False}
    install(root)
    assert status(root)["post-commit"] is True
    assert status(root)["pre-commit"] is False


def test_a_non_repository_is_reported_clearly(tmp_path):
    with pytest.raises(HookError, match="git repository"):
        install(tmp_path / "not_a_repo_at_all")


def test_unsupported_hook_name_is_rejected(tmp_path):
    root = git_repo(tmp_path)
    with pytest.raises(HookError, match="Unsupported hook"):
        install(root, kind="post-merge")


def test_the_hook_body_creates_its_log_directory(tmp_path):
    """Redirecting into a directory that does not exist fails the whole hook.

    With `|| true` swallowing the failure, that left the graph silently stale --
    exactly what the hook exists to prevent.
    """
    root = git_repo(tmp_path)
    body = install(root).read_text()
    assert "mkdir -p .lineagelens" in body
    assert body.index("mkdir -p .lineagelens") < body.index("hook.log")


def test_the_hook_guards_against_ci_and_recursion(tmp_path):
    root = git_repo(tmp_path)
    body = install(root).read_text()
    assert '[ -z "$CI" ]' in body, "CI regenerates the graph as an explicit step"
    assert '[ -z "$LINEAGELENS_HOOK" ]' in body, "recursion guard"


def test_hooks_dir_is_resolved_through_git(tmp_path):
    """Asking git is what makes worktrees and core.hooksPath work."""
    root = git_repo(tmp_path)
    custom = tmp_path / "custom_hooks"
    custom.mkdir()
    subprocess.run(
        ["git", "-C", str(root), "config", "core.hooksPath", str(custom)], check=True
    )
    assert hooks_dir(root) == custom.resolve()
