-- ContextServe Token Ledger & Virtual Keys Schema
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;
PRAGMA synchronous = NORMAL;

-- ============================================================================
-- 1. TENANTS & TEAMS
-- ============================================================================
CREATE TABLE IF NOT EXISTS tenants (
    id                TEXT PRIMARY KEY,              -- 'org_contextserve_001'
    name              TEXT NOT NULL,                 -- 'Core Engineering Platform'
    plan_tier         TEXT NOT NULL DEFAULT 'usage', -- 'developer' | 'growth' | 'enterprise'
    balance_usd       DECIMAL(12, 6) NOT NULL DEFAULT 0.000000, -- Prepaid funds
    currency          TEXT NOT NULL DEFAULT 'USD',
    is_active         BOOLEAN NOT NULL DEFAULT 1,
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ============================================================================
-- 2. VIRTUAL API KEYS
-- ============================================================================
CREATE TABLE IF NOT EXISTS virtual_keys (
    key_hash          TEXT PRIMARY KEY,              -- SHA-256 of issued 'sk-cs-...'
    tenant_id         TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    key_name          TEXT NOT NULL,                 -- e.g. 'LineageLens-MCP-Prod'
    max_budget_usd    DECIMAL(10, 4),                -- Hard limit in USD (NULL = unlimited)
    spend_usd         DECIMAL(10, 4) NOT NULL DEFAULT 0.0000,
    rate_limit_rpm    INTEGER DEFAULT 600,
    rate_limit_tpm    INTEGER DEFAULT 200000,
    allowed_models    TEXT,                          -- JSON array: '["laya-decision", "gpt-4o"]'
    expires_at        TEXT,                          -- ISO-8601 UTC string
    is_active         BOOLEAN NOT NULL DEFAULT 1,
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_virtual_keys_tenant ON virtual_keys(tenant_id);

-- ============================================================================
-- 3. TOKEN INVOCATION LEDGER (Append-Only Time Series)
-- ============================================================================
CREATE TABLE IF NOT EXISTS token_ledger (
    transaction_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    tenant_id         TEXT NOT NULL REFERENCES tenants(id),
    key_hash          TEXT NOT NULL REFERENCES virtual_keys(key_hash),
    request_id        TEXT NOT NULL UNIQUE,          -- UUID generated by LiteLLM Proxy / Gateway
    model_name        TEXT NOT NULL,                 -- 'laya-decision' | 'gpt-4o'
    tier              TEXT NOT NULL,                 -- 'system1' | 'system2'
    prompt_tokens     INTEGER NOT NULL,
    completion_tokens INTEGER NOT NULL,
    total_tokens      INTEGER NOT NULL,
    duration_ms       INTEGER NOT NULL,
    cost_raw_usd      DECIMAL(10, 6) NOT NULL,       -- Raw hardware / provider cost
    billed_amount_usd DECIMAL(10, 6) NOT NULL,       -- Billed amount to tenant (with margin)
    remaining_balance DECIMAL(12, 6) NOT NULL,       -- Remaining tenant balance after deduction
    status            TEXT NOT NULL DEFAULT 'ok',    -- 'ok' | 'blocked_quota' | 'error'
    metadata          TEXT                           -- JSON metadata (repo, branch, agent tool)
);

CREATE INDEX IF NOT EXISTS idx_ledger_tenant_time ON token_ledger(tenant_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_ledger_key ON token_ledger(key_hash);
CREATE INDEX IF NOT EXISTS idx_ledger_model ON token_ledger(model_name);
